/**
 * 大容量原創題庫。
 *
 * 題目以公開課程範圍自行編寫，沒有複製公開試題或評分參考。
 * 參數化題目使用穩定 id，讓模擬卷及本機錯題簿可長期引用同一題目。
 */
(function buildExpandedQuestionBank(){
    "use strict";
    if (window.HKDSE_ICT_EXPANDED || !Array.isArray(window.HKDSE_ICT_QUESTIONS)) return;

    const base = window.HKDSE_ICT_QUESTIONS;
    const additions = [];
    const contexts = ["智慧校園", "社區中心", "網上商店", "醫療診所", "公共圖書館", "運動會", "環保小組", "學校飯堂", "交通資訊站", "慈善機構", "展覽會", "音樂學會", "長者服務中心", "校際比賽", "流動應用程式", "網上預約系統", "校園電視台", "智能溫室", "電子付款服務", "博物館導賞", "義工配對平台", "校巴管理系統", "社區回收站", "網上學習平台", "體育會會員系統", "小型物流公司", "學校圖書館", "診所藥物系統", "公開活動網站", "智能家居裝置"];
    const letters = ["A", "B", "C", "D"];
    const mcq = (prompt, correct, distractors, explanation, errorType="概念混淆") => ({ prompt, correct, distractors, explanation, errorType });
    const short = (prompt, answer, points, errorType="遺漏評分點", type="short-answer") => ({ prompt, answer, points, errorType, type });

    const profiles = {
        "cha-1": { ref:"A(a)", mcq:[mcq("經整理後可支援決策的結果屬於甚麼？","資訊",["原始數據","驗證規則","編碼表"],"數據經處理並具有意義後才成為資訊。"),mcq("輸入、處理、輸出和儲存合稱甚麼？","資訊處理周期",["機器周期","傳輸模式","正規化"],"IPO 加上儲存描述資訊系統的基本處理。")], short:[short("分辨情境中的數據和資訊，並說明資訊的一項決策用途。","未經整理的記錄是數據；經分類或統計、具有意義的結果是資訊，可支援相關決策。",[["指出原始記錄是數據",["數據","原始","記錄"]],["指出處理後結果是資訊",["資訊","分類","統計","處理"]],["提出相關決策用途",["決策","安排","預測","調整"]]])]},
        "cha-2": { ref:"A(b)", mcq:[mcq("哪種方法把輸入與原始文件逐項比較？","Verification",["Range check","Type check","Encryption"],"Verification 檢查抄錄是否準確。"),mcq("欄位只接受 1 至 40 的整數，應同時使用甚麼？","Type check 和 range check",["Parity check 和排序","加密和壓縮","只用 presence check"],"類型檢查整數，範圍檢查界限。")], short:[short("為一個數值欄位建議兩項 validation，並另建議一項 verification。","可使用 type／range／presence 等有效性檢驗；再以雙重輸入或和原始資料比較作驗證。",[["一項合適 validation",["type","類型","range","範圍","presence"]],["第二項不同 validation",["整數","上限","下限","不可留空"]],["一項 verification",["雙重輸入","原始資料","比較","核對"]]])]},
        "cha-3": { ref:"A(c)", mcq:[mcq("1 byte 等於多少 bit？","8",["2","10","16"],"一個 byte 由 8 bit 組成。"),mcq("增加未壓縮點陣圖的色彩深度，通常會怎樣？","增加檔案大小和可表示顏色數",["只降低解像度","刪除所有 metadata","必定變成向量圖"],"每像素使用更多 bit，可表示更多顏色並增加大小。"),mcq("Unicode 相對 ASCII 的主要優點是甚麼？","可表示更多語言字符",["只使用一個 bit","自動壓縮影片","不用儲存空間"],"Unicode 的碼位範圍支援更多文字系統。")], short:[short("計算一幅未壓縮點陣圖的大小，並說明解像度或色彩深度改變的影響。","檔案大小以寬 × 高 × 每像素 bit，再除以 8 得 byte；像素數或每像素 bit 增加會按比例增加大小。",[["使用正確乘法",["寬","高","像素","bit"]],["bit 轉 byte 除以 8",["除以8","除以 8","byte"]],["說明成比例變化",["比例","增加","加倍","每像素"]]])]},
        "cha-4": { ref:"A(d) · 試算表", mcq:[mcq("複製公式時哪種參照會保持欄和列不變？","絕對參照",["相對參照","循環參照","外部排序"],"$A$1 形式鎖定欄及列。"),mcq("要按一個條件計算符合儲存格數量，最合適函數是甚麼？","COUNTIF",["SUM","LEFT","NOW"],"COUNTIF 按指定條件計數。"),mcq("比較各月份銷量最適合哪類圖表？","柱形圖",["只有文字方塊","流程圖","ER 圖"],"柱形圖便於比較不同類別的數值。")], short:[short("寫出可複製的 IF 公式，並說明何時需要絕對參照。","以 IF 比較相對參照的本列資料；固定門檻儲存格要使用 $ 欄 $ 列的絕對參照。",[["使用 IF 及條件",["IF","條件",">=","<="]],["本列資料使用相對參照",["相對","A2","B2"]],["固定門檻使用絕對參照",["絕對","$","固定"]]])]},
        "cha-5": { ref:"A(d) · 數據庫", mcq:[mcq("哪種欄位可唯一識別每筆記錄？","Primary key",["重複欄位","報表標題","任意空值"],"主鍵必須唯一且不可為空。"),mcq("哪個數據庫物件主要用於按條件擷取記錄？","Query",["Form header","Printer driver","Cookie"],"Query 按欄位和條件選取或處理資料。"),mcq("表單的主要用途通常是甚麼？","方便輸入及查看記錄",["取代所有資料表","編譯程式","加密硬碟"],"表單提供受控的資料輸入介面。")], short:[short("為兩個相關資料表指出主鍵、外鍵及關係。","父表以唯一欄位作主鍵；子表保存外鍵指向父表，常形成一對多關係。",[["指出父表主鍵",["主鍵","PK","唯一"]],["指出子表外鍵",["外鍵","FK","指向"]],["說明一對多關係",["一對多","1:M","多筆"]]])]},
        "chb-1": { ref:"B(a)", mcq:[mcq("CPU 中執行算術及邏輯運算的是甚麼？","ALU",["Control unit","Hard disk","NIC"],"ALU 處理算術和邏輯運算。"),mcq("哪種記憶體通常在斷電後失去內容？","RAM",["ROM","SSD","Blu-ray"],"RAM 是揮發性主記憶體。"),mcq("機器周期中首先從記憶體取得指令的階段是甚麼？","Fetch",["Store","Print","Encrypt"],"Fetch 由記憶體取得下一指令。")], short:[short("描述 fetch、decode、execute 三個階段及一個相關暫存器。","CPU 以 PC／MAR 取得指令，控制單元解碼，ALU 或其他部件執行；PC、MAR、MDR、CIR 均可按階段解釋。",[["正確描述 fetch",["fetch","取得","記憶體","PC","MAR"]],["正確描述 decode",["decode","解碼","控制單元"]],["正確描述 execute",["execute","執行","ALU"]]])]},
        "chb-2": { ref:"B(b)", mcq:[mcq("讓操作系統控制新硬件的軟件稱為甚麼？","Device driver",["Spreadsheet","Cookie","Query"],"Driver 在操作系統和硬件之間提供介面。"),mcq("銀行月結單集中於非繁忙時間處理屬甚麼模式？","Batch processing",["Real-time control","Interactive graphics","Manual sorting"],"批次處理把工作收集後成批執行。"),mcq("防毒及備份軟件通常屬於甚麼？","Utility software",["CPU register","Source data","HTML tag"],"Utility software 維護、保護或管理系統。")], short:[short("按情境選擇 batch、interactive 或 real-time processing，並解釋。","選擇要按回應時間及工作方式：批次集中處理；互動式立即回應使用者；實時控制需在期限內回應事件。",[["選擇合適模式",["batch","批次","interactive","互動","real-time","實時"]],["連結回應時間",["即時","期限","延遲","回應"]],["連結工作方式",["集中","使用者","感應器","控制"]]])]},
        "chc-1": { ref:"C(a) · 網絡", mcq:[mcq("在星形網絡中集中連接有線裝置的設備是甚麼？","Switch",["Scanner","Projector","Microphone"],"Switch 在 LAN 內轉送 frame。"),mcq("讓無線裝置接入有線 LAN 的設備是甚麼？","Wireless access point",["CPU fan","Barcode reader","Plotter"],"AP 橋接無線和有線網絡。"),mcq("連接不同 IP 網絡並選擇路徑的設備是甚麼？","Router",["Keyboard","RAM","Speaker"],"Router 根據 IP 位址轉送 packet。")], short:[short("為一個小型 LAN 選擇 switch、router 及 wireless access point，說明各自作用。","Switch 連接有線裝置；AP 提供 Wi-Fi 接入 LAN；router 連接不同網絡及轉送 IP packet。",[["Switch 作用",["switch","有線","LAN","frame"]],["AP 作用",["access point","AP","Wi-Fi","無線"]],["Router 作用",["router","不同網絡","IP","packet"]]])]},
        "chc-2": { ref:"C(a) · 協定", mcq:[mcq("把域名轉換成 IP 位址的服務是甚麼？","DNS",["FTP","HTML","USB"],"DNS 執行名稱解析。"),mcq("可靠傳輸、排序及重傳主要由哪個協定處理？","TCP",["JPEG","CSS","ASCII"],"TCP 提供可靠的連接導向傳輸。"),mcq("URL 中 https 表示甚麼？","Scheme／protocol",["檔案大小","MAC address","主鍵"],"URL scheme 指定存取資源的方法。")], short:[short("由輸入網址至載入網頁，順序說明 DNS、IP、TCP 及 HTTP／HTTPS。","DNS 把域名解析為 IP；以 IP 尋找主機；TCP 建立可靠連線；HTTP／HTTPS 傳送 request 和 response。",[["DNS 解析",["DNS","域名","IP"]],["TCP 連線",["TCP","可靠","連線"]],["HTTP request／response",["HTTP","HTTPS","request","response"]]])]},
        "chc-3": { ref:"C(b)", mcq:[mcq("評估網上資料可信性時，哪項最重要？","核對作者、日期、證據和其他來源",["只看第一個結果","只按圖片顏色","轉發次數愈多愈可靠"],"來源、時效、證據和交叉核對比排名可靠。"),mcq("串流播放前先保存少量內容以減少停頓稱為甚麼？","Buffering",["Normalisation","Indexing key","Defragmentation"],"Buffer 吸收短暫網絡速度波動。"),mcq("把運算和儲存按需要由網絡服務提供屬甚麼？","Cloud computing",["ASCII","Standalone ROM","Paper filing"],"雲端服務透過網絡提供共享資源。")], short:[short("提出三項評估網上消息可信性的方法。","檢查作者／機構、發布日期、證據和引用，並以獨立可靠來源交叉核對。",[["檢查作者或機構",["作者","機構","來源"]],["檢查日期或證據",["日期","證據","引用"]],["交叉核對",["交叉","多個來源","核對"]]])]},
        "chc-4": { ref:"C(c)", mcq:[mcq("哪個 HTML 元素表示最大的主標題？","h1",["img","br","td"],"h1 表示最高層級標題。"),mcq("為圖片加入替代文字的主要好處是甚麼？","支援屏幕閱讀器及圖片未載入情況",["自動加密網站","增加 CPU 核心","取代所有導覽"],"alt 文字描述圖片內容。"),mcq("跨頁一致導覽最能改善甚麼？","可用性",["色彩深度","二進制精度","資料庫正規化"],"一致導覽降低使用者尋找功能的負擔。")], short:[short("改善一個網頁的導覽、可讀性及無障礙使用。","使用一致且具描述的導覽；確保字色對比和合適字體；為圖片、表單及結構加入替代文字和標籤。",[["改善導覽",["導覽","一致","描述"]],["改善可讀性",["對比","字體","留白"]],["改善無障礙",["alt","替代文字","label","鍵盤"]]])]},
        "chc-5": { ref:"C(d)", mcq:[mcq("把檔案加密並索取贖金的惡意程式是甚麼？","Ransomware",["Device driver","Compiler","Spreadsheet"],"勒索軟件會限制資料存取並索款。"),mcq("以大量請求令服務不能正常回應屬甚麼攻擊？","DoS／DDoS",["Normalisation","Binary search","Mail merge"],"DoS 以資源耗盡破壞可用性。"),mcq("數碼簽署主要證明甚麼？","完整性和來源認證",["資料一定保密","硬碟容量","網速加倍"],"簽署驗證內容未被改動及簽署者身分。")], short:[short("為一項網上服務提出三層保安措施並說明風險。","可用強密碼及多因素認證、HTTPS 加密傳輸、防火牆／更新／備份；措施應分別連到冒認、截取、入侵或資料損失風險。",[["認證措施",["強密碼","多因素","2FA","認證"]],["傳輸或網絡措施",["HTTPS","加密","防火牆"]],["維護或復原措施",["更新","patch","備份","復原"]]])]},
        "chd-1": { ref:"D(a)", mcq:[mcq("把大問題分成較小子問題稱為甚麼？","Decomposition",["Compression","Encryption","Rasterisation"],"分解有助逐部分設計和測試。"),mcq("忽略不影響解法的細節稱為甚麼？","Abstraction",["Verification","Formatting","Streaming"],"抽象化保留與解法相關的特徵。"),mcq("辨認不同問題間的共通結構稱為甚麼？","Pattern recognition",["Copyright","Defragmentation","Access right"],"模式辨認有助重用解法。")], short:[short("把情境分解成輸入、處理、輸出及兩個子問題。","先列出必要輸入、主要處理和輸出，再把工作拆成職責清晰而可獨立測試的子問題。",[["正確輸入",["輸入","input"]],["正確處理和輸出",["處理","processing","輸出","output"]],["合理分解",["子問題","分解","模組"]]])]},
        "chd-2": { ref:"D(b)", mcq:[mcq("流程圖的菱形通常表示甚麼？","Decision",["Start／End","Input only","File storage"],"菱形表示條件判斷及分支。"),mcq("重複執行一組步驟使用哪種控制結構？","Iteration",["Sequence only","Copyright","Index"],"Iteration 依條件或次數重複。"),mcq("保存多個同類項目的合適結構是甚麼？","Array／list",["單一 Boolean 常數","HTML heading","Firewall rule"],"陣列以索引存取多個同類值。")], short:[short("把一個有輸入、判斷和重複的算法寫成偽代碼，並指出三種控制結構。","算法應包含 sequence、selection 和 iteration，並以清楚縮排表示其範圍。",[["Sequence",["sequence","順序","INPUT","OUTPUT"]],["Selection",["IF","ELSE","selection","選擇"]],["Iteration",["FOR","WHILE","REPEAT","iteration","重複"]]])]},
        "chd-3": { ref:"D(c)", mcq:[mcq("條件只在某情況成立時執行應使用甚麼？","if statement",["Only print","Copyright licence","DNS"],"if 根據 Boolean 條件選擇流程。"),mcq("已知重複次數時通常最適合甚麼迴圈？","for loop",["Infinite while only","HTML table","Firewall"],"for 適合按序列或固定次數迭代。"),mcq("取得文字長度通常使用甚麼概念？","Length function",["Router port","Primary key","Pixel depth"],"字串函數可計算字符數。")], short:[short("追蹤一段含迴圈及累加器的程式，寫出每輪變數及最終輸出。","先初始化 accumulator；每輪按輸入更新並記錄；迴圈結束後輸出最後累積值。",[["正確初始化",["初始化","0","initial"]],["逐輪更新",["每輪","累加","更新","trace"]],["正確最終輸出",["輸出","最後","總和"]]])]},
        "chd-4": { ref:"D(d)", mcq:[mcq("測試接受範圍 1 至 100 時，哪組最接近邊界數據？","1 和 100",["50 和 60","ABC 和空白","只有 1000"],"邊界數據位於有效範圍兩端。"),mcq("程式能執行但給出錯誤結果屬甚麼？","Logic error",["Syntax error only","No error","Copyright"],"邏輯錯誤不一定阻止程式執行。"),mcq("逐行記錄變數值的表稱為甚麼？","Trace table",["ER diagram","Cookie","Histogram only"],"Trace table 協助找出流程和變數錯誤。")], short:[short("為一個有限輸入範圍設計正常、邊界及不合法測試，寫出預期結果。","正常值應被接受；上下界要被接受；界外或錯誤類型應被拒絕並顯示清楚訊息。",[["正常測試",["正常","中間","接受"]],["邊界測試",["邊界","上限","下限"]],["不合法測試",["不合法","界外","拒絕","錯誤訊息"]]])]},
        "che-1": { ref:"E(a)", mcq:[mcq("由標註數據學習分類規則屬甚麼？","Supervised learning",["手動排序紙張","純粹壓縮","DNS lookup"],"監督學習使用有標籤例子訓練模型。"),mcq("把數碼內容疊加到現實畫面稱為甚麼？","Augmented reality",["Virtual memory","Batch processing","Normalisation"],"AR 保留現實視野並加入數碼元素。"),mcq("3D 打印一般使用哪種製作方式？","逐層增材製造",["只刪除像素","遠端登入","關聯連接"],"3D 打印按模型逐層加入物料。")], short:[short("比較 AR 與 VR，並為一個情境選擇合適技術。","AR 在現實畫面上疊加數碼資訊；VR 以沉浸式虛擬環境取代現實視野；選擇要按是否仍需看見真實環境。",[["正確描述 AR",["AR","疊加","現實"]],["正確描述 VR",["VR","沉浸","虛擬環境"]],["按情境選擇及解釋",["選擇","需要","真實環境"]]])]},
        "che-2": { ref:"E(b)", mcq:[mcq("長時間重複使用滑鼠最相關的健康風險是甚麼？","RSI",["Data redundancy","Packet loss only","Copyright expiry"],"重複動作和不良姿勢可造成重複性勞損。"),mcq("部分群體缺乏裝置、連線或技能稱為甚麼？","Digital divide",["Binary overflow","Foreign key","Cache hit"],"數碼鴻溝描述 ICT 接達和能力差異。"),mcq("收集個人資料前最重要的原則之一是甚麼？","目的清楚並只收集必要資料",["盡量收集所有資料","永久公開","不需通知"],"資料最少化和目的限制可減低私隱風險。")], short:[short("分析一項 ICT 應用的持份者、好處、風險和一項緩解措施。","指出受影響群體，平衡效率／接達等好處與私隱／偏差／排除風險，再提出可行控制。",[["指出持份者及好處",["持份者","好處","效率","接達"]],["指出具體風險",["私隱","偏差","排除","風險"]],["提出緩解措施",["同意","最少化","審核","無障礙"]]])]},
        "che-3": { ref:"E(c)", mcq:[mcq("容許查看及按授權修改源代碼的軟件稱為甚麼？","Open source software",["Public domain 必然","只有 shareware","硬件驅動器"],"開放源碼仍受授權條款約束。"),mcq("可嵌入作品以協助證明來源的技術是甚麼？","Digital watermark",["DHCP","Defragmentation","Parity bit only"],"數碼水印可加入識別資訊。"),mcq("未經許可大量分發受版權保護作品通常屬甚麼？","Copyright infringement",["Fair use 一定成立","Database index","Real-time processing"],"複製及分發權一般屬版權持有人。")], short:[short("比較 freeware、shareware 和 open source 的價格、試用限制及源代碼權利。","Freeware 通常免費使用但不必提供源碼；shareware 常設試用或功能限制；open source 按授權提供源碼和修改／分發權。",[["Freeware 特點",["freeware","免費","源碼"]],["Shareware 特點",["shareware","試用","限制"]],["Open source 特點",["open source","開放源碼","授權","修改"]]])]},
        "ea-1": { ref:"Elective A(a)", mcq:[mcq("可唯一識別記錄的最小欄位組合稱為甚麼？","Candidate key",["Foreign row","Report footer","Cookie"],"候選鍵具有唯一性和最小性。"),mcq("外鍵指向不存在的父記錄會違反甚麼？","Referential integrity",["Colour depth","Batch mode","Copyright"],"參照完整性要求非空外鍵有相符父記錄。"),mcq("交易失敗時撤銷未完成變更稱為甚麼？","Rollback",["Index","Query view","Streaming"],"Rollback 把資料庫回復到一致狀態。")], short:[short("說明 primary、candidate、foreign key 及三種完整性。","候選鍵可唯一識別記錄；選一個作主鍵；外鍵連到另一表。實體、參照及 domain 完整性分別保護識別、關係和有效值。",[["鍵的分工",["候選鍵","主鍵","外鍵"]],["實體完整性",["實體完整性","唯一","非空"]],["參照或 domain 完整性",["參照完整性","domain","存在","範圍"]]])]},
        "ea-2": { ref:"Elective A(b)", mcq:[mcq("在分組後篩選 aggregate 結果使用甚麼？","HAVING",["WHERE only","ALTER","DROP"],"HAVING 篩選 GROUP BY 後的群組。"),mcq("保留左表所有記錄的連接是甚麼？","LEFT OUTER JOIN",["INNER JOIN only","UNION column","Primary key"],"左外連接保留未配對左表記錄。"),mcq("改變現有記錄值使用甚麼 SQL？","UPDATE",["SELECT only","CREATE VIEW only","ORDER BY only"],"UPDATE 配合 SET 修改記錄。")], short:[short("寫出按條件連接兩表、分組及篩選 aggregate 結果的 SQL。","SELECT 所需欄位及 aggregate，FROM／JOIN 相關表並寫連接條件，GROUP BY 非聚合欄，HAVING 篩選群組。",[["SELECT 和 aggregate",["SELECT","COUNT","SUM","AVG"]],["JOIN 條件",["JOIN","ON","="]],["GROUP BY 和 HAVING",["GROUP BY","HAVING"]]],"SQL 結構錯誤","sql")]},
        "ea-3": { ref:"Elective A(c)", mcq:[mcq("M:N 關係應如何轉成關聯表？","加入橋接表並拆成兩個 1:M",["刪除一個實體","取消所有鍵","把多值放同一格"],"橋接表保存兩邊外鍵和關係屬性。"),mcq("2NF 主要移除甚麼？","Partial dependency",["所有外鍵","所有索引","HTTPS"],"2NF 要求非鍵完整依賴整個複合鍵。"),mcq("反正規化的常見代價是甚麼？","增加冗餘和一致性維護",["一定刪除資料","不能查詢","沒有任何代價"],"反正規化可改善讀取但增加重複。")], short:[short("把含複合鍵、partial 及 transitive dependency 的表正規化至 3NF。","先達 1NF；把只依賴部分複合鍵的欄位分表達 2NF；再移除非鍵對非鍵的傳遞依賴達 3NF，列出各表鍵。",[["說明 1NF",["1NF","單一值","repeating"]],["移除 partial dependency",["2NF","partial","部分依賴"]],["移除 transitive dependency 並列鍵",["3NF","transitive","傳遞依賴","主鍵"]]])]},
        "eb-1": { ref:"Elective B(a)", mcq:[mcq("自動配發 IP 設定的伺服器是甚麼？","DHCP server",["Web server","Database server","Print-only client"],"DHCP 租用 IP、mask、gateway 等設定。"),mcq("集中處理網域登入和政策的是甚麼？","Domain controller",["Image editor","Spreadsheet","Access point only"],"Domain controller 管理網域身分和政策。"),mcq("POST 相對 GET 的正確描述是甚麼？","資料通常放在 request body，但仍需 HTTPS",["自動端對端加密","一定只可讀取","不用 server"],"方法和加密是不同層次。")], short:[short("按情境配對 DHCP、proxy、domain controller、file、web 和 database server。","DHCP 配發設定；proxy 代表客戶端套用政策；domain controller 集中登入；file server 分享檔案；web server 回應 HTTP；database server 處理資料。",[["配對位址或登入服務",["DHCP","domain controller","登入"]],["配對 proxy 或 file server",["proxy","file server","檔案","政策"]],["配對 web／database",["web server","database server","HTTP","查詢"]]])]},
        "eb-2": { ref:"Elective B(b)", mcq:[mcq("客戶端 validation 的主要限制是甚麼？","可被停用或繞過",["不能顯示文字","一定比 server 慢","不能使用 CSS"],"伺服器必須重新驗證。"),mcq("Cookie 最適合保存甚麼？","短期 session identifier 或偏好",["明文密碼","整個數據庫","私人密碼匙"],"Cookie 不應保存可直接冒認的秘密。"),mcq("CSS 的主要用途是甚麼？","集中控制呈現和一致風格",["執行 SQL","分配 IP","編譯 CPU 指令"],"CSS 把呈現規則與內容結構分開。")], short:[short("順序說明 HTML／CSS、client script、POST、server script、database 和 response。","HTML／CSS 建立結構和呈現；client script 提供即時檢查；POST 送資料；server 再驗證及處理；database 受控讀寫；response 回傳結果。",[["HTML／CSS 和 client",["HTML","CSS","client","JavaScript"]],["POST 和 server validation",["POST","server","再次驗證"]],["Database 和 response",["database","數據庫","response"]]])]},
        "ec-1": { ref:"Elective C(a)", mcq:[mcq("Binary search 的必要前提是甚麼？","資料已排序",["資料必須是圖片","只能有一項","不用比較"],"二分搜尋依靠有序關係排除一半。"),mcq("Stack 的移除次序是甚麼？","LIFO",["FIFO","Random only","Alphabetical"],"最後加入的項目最先移除。"),mcq("Selection sort 每輪主要做甚麼？","在未排序部分找極值再交換",["只比較中間項","建立外鍵","發出 HTTP request"],"Selection sort 每輪選出一個極值。")], short:[short("比較 linear 和 binary search，並按資料條件作選擇。","Linear search 逐項比較且不需排序；binary search 每次排除一半但要求資料有序；選擇須按排序狀態、規模及搜尋次數。",[["Linear 特點",["linear","逐項","不用排序"]],["Binary 特點",["binary","減半","已排序"]],["按情境選擇",["規模","搜尋次數","選擇"]]])]},
        "ec-2": { ref:"Elective C(b)", mcq:[mcq("讀取環境數值的硬件通常稱為甚麼？","Sensor",["Actuator only","CSS selector","Primary key"],"Sensor 把實體狀態轉成輸入。"),mcq("馬達在控制系統中通常屬於甚麼？","Actuator／output",["Candidate key","Cookie","Source code comment"],"Actuator 把控制訊號轉成實體動作。"),mcq("兩個開關閾值可減少甚麼？","臨界值附近頻繁切換",["所有程式碼","資料庫主鍵","HTML headings"],"Hysteresis 保留中間狀態。")], short:[short("以 input、event handler、processing、output 和安全失效解釋實體裝置。","Sensor 或使用者事件提供 input；handler 判斷狀態；library 控制 actuator 產生 output；異常或 timeout 時進入安全狀態。",[["Input／event",["sensor","事件","input"]],["Handler／processing／output",["handler","處理","actuator","output"]],["安全失效",["timeout","安全狀態","警報","停止"]]])]}
    };

    const visualQuestions = [
        { id:"q-case-campus-01",topicId:"chc-1",syllabusRef:"C(a)",difficulty:"standard",marks:4,type:"short-answer",caseId:"smart-campus",caseTitle:"智慧校園網絡更新",partLabel:"(a)",question:"根據圖示，說明 S、R 和 AP 三項設備的作用。",visual:{type:"network",title:"校園網絡",nodes:["Internet","R","S","Server","AP","Tablet"],links:[["Internet","R"],["R","S"],["S","Server"],["S","AP"],["AP","Tablet"]]},answer:"R 是 router，連接校園 LAN 與 Internet；S 是 switch，集中連接有線裝置；AP 讓平板以 Wi-Fi 接入 LAN。",markingScheme:[{marks:1,criterion:"辨認 R 為 router。",anyOf:["R","router","路由器"]},{marks:1,criterion:"說明 router 連接不同網絡。",anyOf:["Internet","不同網絡","LAN"]},{marks:1,criterion:"說明 switch 連接有線裝置。",anyOf:["switch","有線","Server"]},{marks:1,criterion:"說明 AP 提供無線接入。",anyOf:["AP","Wi-Fi","無線"]}],explanation:"先按連接位置辨認設備，再說明它處理的網絡範圍。",errorType:"網絡設備混淆"},
        { id:"q-case-campus-02",topicId:"chc-5",syllabusRef:"C(d)",difficulty:"standard",marks:4,type:"short-answer",caseId:"smart-campus",caseTitle:"智慧校園網絡更新",partLabel:"(b)",question:"校外使用者嘗試以猜密碼登入 Server。建議兩項保安措施並分別說明。",visual:{type:"news",title:"保安記錄摘要",headline:"15 分鐘內出現 1,240 次失敗登入",facts:["來源：多個海外 IP","帳戶：teacher-admin","現有設定：只用密碼"]},answer:"可使用多因素認證，令密碼外洩仍不足以登入；限制登入嘗試／延遲或鎖定帳戶，減低暴力猜測；亦可設強密碼、VPN 或 IP 限制。",markingScheme:[{marks:1,criterion:"第一項合適措施。",anyOf:["多因素","2FA","強密碼","限制"]},{marks:1,criterion:"解釋第一項如何減低猜密碼風險。",anyOf:["外洩","不足","猜測","暴力"]},{marks:1,criterion:"第二項不同措施。",anyOf:["鎖定","延遲","VPN","IP"]},{marks:1,criterion:"解釋第二項作用。",anyOf:["次數","阻止","限制","認證"]}],explanation:"答案要把措施直接連到大量失敗登入這項證據。",errorType:"保安措施未連結風險"},
        { id:"q-case-campus-03",topicId:"cha-4",syllabusRef:"A(d)",difficulty:"standard",marks:4,type:"short-answer",caseId:"smart-campus",caseTitle:"智慧校園網絡更新",partLabel:"(c)",question:"工作表記錄每個 AP 的每日流量。寫出 E2 計算三日總量的公式及 F2 判斷是否超過固定上限 H1 的公式。",visual:{type:"spreadsheet",title:"AP 流量（GB）",columns:["A","B","C","D","E","F"],rows:[["AP","Mon","Tue","Wed","Total","Alert"],["AP01","42","51","48","?","?"],["AP02","35","39","41","?","?"]]},answer:"E2：=SUM(B2:D2)；F2：=IF(E2>$H$1,\"Alert\",\"OK\")。",markingScheme:[{marks:1,criterion:"使用 SUM。",anyOf:["SUM"]},{marks:1,criterion:"範圍 B2:D2 正確。",anyOf:["B2:D2"]},{marks:1,criterion:"使用 IF 比較 E2。",anyOf:["IF","E2"]},{marks:1,criterion:"以 $H$1 絕對參照固定上限。",anyOf:["$H$1"]}],explanation:"每列資料要相對移動，但共同門檻 H1 必須鎖定。",errorType:"試算表參照錯誤"},
        { id:"q-case-campus-04",topicId:"che-2",syllabusRef:"E(b)",difficulty:"advanced",marks:4,type:"short-answer",caseId:"smart-campus",caseTitle:"智慧校園網絡更新",partLabel:"(d)",question:"系統擬永久保存所有學生裝置的完整瀏覽記錄。指出兩項私隱問題及一項改良。",visual:{type:"chart",title:"建議保存期",labels:["登入記錄","網站類別","完整網址","裝置位置"],values:[30,180,365,365],unit:"日"},answer:"完整網址和位置可揭示個人習慣，永久或過長保存超出需要並增加外洩影響。應只收集達成保安目的所需資料、縮短保存期、限制存取及匿名化。",markingScheme:[{marks:1,criterion:"指出記錄可揭示個人行為／位置。",anyOf:["習慣","行為","位置","私隱"]},{marks:1,criterion:"指出過長保存或超出目的。",anyOf:["永久","過長","目的","不必要"]},{marks:1,criterion:"提出資料最少化／縮短期限。",anyOf:["最少化","縮短","刪除","必要"]},{marks:1,criterion:"提出存取控制或匿名化。",anyOf:["存取權","匿名","加密"]}],explanation:"私隱分析要同時處理收集範圍、保存時間和可存取人士。",errorType:"倫理分析不完整"},
        { id:"q-case-clinic-01",topicId:"chb-1",syllabusRef:"B(a)",difficulty:"standard",marks:4,type:"short-answer",caseId:"clinic-system",caseTitle:"診所輪候系統",partLabel:"(a)",question:"按 CPU 結構圖描述一次 fetch 的資料流。",visual:{type:"cpu",title:"CPU 與記憶體",blocks:["PC","MAR","Memory","MDR","CIR","Control Unit","ALU"],arrows:["PC→MAR","MAR→Memory","Memory→MDR","MDR→CIR"]},answer:"PC 保存下一指令位址並複製到 MAR；記憶體按位址讀出指令至 MDR，再送入 CIR；PC 更新指向下一指令。",markingScheme:[{marks:1,criterion:"PC 保存／送出下一指令位址。",anyOf:["PC","下一指令","位址"]},{marks:1,criterion:"位址送到 MAR。",anyOf:["MAR"]},{marks:1,criterion:"指令由 memory 到 MDR。",anyOf:["Memory","記憶體","MDR"]},{marks:1,criterion:"指令送到 CIR／PC 更新。",anyOf:["CIR","PC 更新"]}],explanation:"Fetch 題要分清位址路徑和指令內容路徑。",errorType:"CPU 資料流次序錯誤"},
        { id:"q-case-clinic-02",topicId:"chd-2",syllabusRef:"D(b)",difficulty:"standard",marks:4,type:"short-answer",caseId:"clinic-system",caseTitle:"診所輪候系統",partLabel:"(b)",question:"根據流程圖，指出當 priority=TRUE 且 queueFull=FALSE 時的輸出，並解釋兩個 decision。",visual:{type:"flowchart",title:"輪候處理",steps:["START","INPUT priority, queueFull","queueFull?","DISPLAY Full","priority?","ADD to front","ADD to rear","END"]},answer:"queueFull 為 FALSE，所以不顯示 Full；priority 為 TRUE，病人加入 queue front。第一判斷防止 overflow，第二判斷決定優先位置。",markingScheme:[{marks:1,criterion:"不顯示 Full。",anyOf:["不顯示","FALSE"]},{marks:1,criterion:"加入 queue front。",anyOf:["front","隊首","前端"]},{marks:1,criterion:"queueFull 判斷防止 overflow。",anyOf:["overflow","滿"]},{marks:1,criterion:"priority 決定加入位置。",anyOf:["priority","優先","位置"]}],explanation:"先沿指定 TRUE／FALSE 分支追蹤，再交代每個 decision 的功能。",errorType:"流程圖追蹤錯誤"},
        { id:"q-case-clinic-03",topicId:"chd-3",syllabusRef:"D(c)",difficulty:"standard",marks:4,type:"short-answer",caseId:"clinic-system",caseTitle:"診所輪候系統",partLabel:"(c)",question:"完成追蹤表，寫出程式結束時 total 和 count。",questionCode:"total = 0\ncount = 0\nfor wait in [12, 35, 8, 41]:\n    if wait > 30:\n        total = total + wait\n        count = count + 1",visual:{type:"trace",title:"變數追蹤",columns:["wait","wait > 30","total","count"],rows:[["12","False","0","0"],["35","True","?","?"],["8","False","?","?"],["41","True","?","?"]]},answer:"處理 35 後 total=35、count=1；8 不改變；處理 41 後 total=76、count=2。",markingScheme:[{marks:1,criterion:"35 後 total=35。",anyOf:["35"]},{marks:1,criterion:"35 後 count=1。",anyOf:["count=1","count 1"]},{marks:1,criterion:"最終 total=76。",anyOf:["76"]},{marks:1,criterion:"最終 count=2。",anyOf:["count=2","count 2"]}],explanation:"只有 wait 大於 30 時才同時更新兩個變數。",errorType:"程式追蹤錯誤"},
        { id:"q-case-clinic-04",topicId:"cha-2",syllabusRef:"A(b)",difficulty:"standard",marks:3,type:"short-answer",caseId:"clinic-system",caseTitle:"診所輪候系統",partLabel:"(d)",question:"Age 接受 0 至 120 的整數。建議 type、range 及 verification 方法。",visual:{type:"table",title:"輸入樣本",columns:["PatientID","Age","Source"],rows:[["P104","38","紙本登記表"],["P105","12O","紙本登記表"],["P106","-4","紙本登記表"]]},answer:"Type check 確保是整數；range check 確保 0–120；verification 可把輸入與紙本表比較或雙重輸入。",markingScheme:[{marks:1,criterion:"Type check：整數。",anyOf:["type","類型","整數"]},{marks:1,criterion:"Range check：0–120。",anyOf:["range","範圍","0","120"]},{marks:1,criterion:"和來源比較／雙重輸入。",anyOf:["紙本","原始","比較","雙重輸入"]}],explanation:"12O 是類型／格式問題，-4 是範圍問題；verification 另檢查抄錄準確。",errorType:"Validation／verification 混淆"},
        { id:"q-case-shop-01",topicId:"chc-4",syllabusRef:"C(c)",difficulty:"standard",marks:4,type:"short-answer",caseId:"online-shop",caseTitle:"校服網上商店",partLabel:"(a)",question:"指出版面兩項可用性問題，並各提出一項改善。",visual:{type:"webpage",title:"商品頁線框",regions:["LOGO","超細灰字商品名稱","紅底綠字價格","只有圖示的購物車按鈕","Footer"]},answer:"文字過細應增大並使用可縮放字體；紅綠低辨識度應提高對比及不用顏色作唯一提示；圖示按鈕應加文字或 aria-label。",markingScheme:[{marks:1,criterion:"指出第一項具體問題。",anyOf:["細","對比","顏色","圖示"]},{marks:1,criterion:"提出對應改善。",anyOf:["增大","提高對比","文字","label"]},{marks:1,criterion:"指出第二項不同問題。",anyOf:["紅綠","購物車","按鈕","灰字"]},{marks:1,criterion:"提出第二項對應改善。",anyOf:["不用顏色","描述","aria","可讀"]}],explanation:"改善必須和圖中可觀察問題逐一配對。",errorType:"網頁設計理據不足"},
        { id:"q-case-shop-02",topicId:"cha-3",syllabusRef:"A(c)",difficulty:"standard",marks:3,type:"short-answer",caseId:"online-shop",caseTitle:"校服網上商店",partLabel:"(b)",question:"商品圖像為 1200 × 800、24-bit。計算未壓縮大小（byte），並說明 JPEG 的一項取捨。",visual:{type:"image-grid",title:"商品圖像",images:[{src:"assets/images/network/network-switch.jpg",label:"示例商品相片格式：JPEG"}]},answer:"1200 × 800 × 24 ÷ 8 = 2,880,000 byte。JPEG 有損壓縮可大幅減小相片檔案，但可能降低畫質。",markingScheme:[{marks:1,criterion:"正確算式並除以 8。",anyOf:["1200","800","24","8"]},{marks:1,criterion:"答案 2,880,000 byte。",anyOf:["2880000","2,880,000"]},{marks:1,criterion:"說明有損壓縮的大小／畫質取捨。",anyOf:["有損","減小","畫質"]}],explanation:"未壓縮大小按像素和色彩深度計算；檔案格式選擇另涉及品質。",errorType:"多媒體大小計算錯誤"},
        { id:"q-case-shop-03",topicId:"che-3",syllabusRef:"E(c)",difficulty:"standard",marks:3,type:"short-answer",caseId:"online-shop",caseTitle:"校服網上商店",partLabel:"(c)",question:"設計員從搜尋引擎下載相片並刪除水印後使用。指出問題和兩項正確做法。",visual:{type:"news",title:"素材紀錄",headline:"圖片來源欄只寫「Internet」",facts:["沒有授權證明","已移除水印","用於公開商店"]},answer:"搜尋到不等於取得使用權，移除水印亦可能掩蓋權利資訊。應取得版權持有人許可／合適授權，或使用自行拍攝、公共領域或符合條款的素材並標示來源。",markingScheme:[{marks:1,criterion:"指出可能侵犯版權／移除水印問題。",anyOf:["版權","侵權","水印"]},{marks:1,criterion:"取得許可或合適授權。",anyOf:["許可","授權"]},{marks:1,criterion:"使用合法替代來源並遵守標示。",anyOf:["自行拍攝","公共領域","Creative Commons","標示"]}],explanation:"網上可見並不代表可自由複製；使用方式須符合授權。",errorType:"知識產權概念錯誤"},
        { id:"q-case-shop-04",topicId:"chc-3",syllabusRef:"C(b)",difficulty:"standard",marks:3,type:"short-answer",caseId:"online-shop",caseTitle:"校服網上商店",partLabel:"(d)",question:"根據兩個消息來源，提出三項核實價格新聞的方法。",visual:{type:"news",title:"兩個網上消息",headline:"「下月所有校服價格上升 50%」",facts:["匿名社交帳戶：沒有證據，今日發布","供應商公告：具日期、聯絡資料和價格表"]},answer:"核對作者／機構身分，檢查日期和原始價格表證據，並向供應商或其他獨立可靠來源交叉核對。",markingScheme:[{marks:1,criterion:"核對作者／機構。",anyOf:["作者","機構","匿名"]},{marks:1,criterion:"檢查日期和證據。",anyOf:["日期","價格表","證據"]},{marks:1,criterion:"以獨立來源交叉核對。",anyOf:["交叉","其他來源","供應商"]}],explanation:"不要單憑排名、轉發或語氣判斷可信性。",errorType:"資訊可信性分析不足"},
        { id:"q-visual-ea-erd",topicId:"ea-3",syllabusRef:"Elective A(c)",difficulty:"advanced",marks:5,type:"short-answer",question:"根據 ER 圖把 M:N 關係轉成三個關聯表，列出鍵。",visual:{type:"erd",title:"借用關係",entities:["MEMBER(MemberID, Name)","BORROW(BorrowDate, ReturnDate)","BOOK(BookID, Title)"],cardinality:["1:M","M:1"]},answer:"MEMBER(MemberID PK, Name)、BOOK(BookID PK, Title)、BORROW(MemberID PK/FK, BookID PK/FK, BorrowDate, ReturnDate)。BORROW 以兩外鍵作複合主鍵，把 M:N 拆成兩個 1:M。",markingScheme:[{marks:1,criterion:"MEMBER 主鍵。",anyOf:["MemberID","MEMBER"]},{marks:1,criterion:"BOOK 主鍵。",anyOf:["BookID","BOOK"]},{marks:1,criterion:"建立 BORROW。",anyOf:["BORROW"]},{marks:1,criterion:"兩外鍵作複合主鍵。",anyOf:["複合","PK/FK","外鍵"]},{marks:1,criterion:"拆成兩個 1:M。",anyOf:["1:M","一對多"]}],explanation:"關係本身的日期屬性放在橋接表。",errorType:"ER 轉表錯誤"},
        { id:"q-visual-ea-sql",topicId:"ea-2",syllabusRef:"Elective A(b)",difficulty:"advanced",marks:5,type:"sql",question:"根據兩表寫 SQL，顯示每個類別的平均價格，只保留平均價格高於 100 的類別。",visual:{type:"table",title:"資料表結構",columns:["PRODUCT","CATEGORY"],rows:[["PID PK, PName, Price, CatID FK","CatID PK, CatName"]]},answer:"SELECT C.CatName, AVG(P.Price) FROM CATEGORY C INNER JOIN PRODUCT P ON C.CatID=P.CatID GROUP BY C.CatName HAVING AVG(P.Price)>100;",markingScheme:[{marks:1,criterion:"SELECT CatName 及 AVG(Price)。",anyOf:["SELECT","CATNAME","AVG"]},{marks:1,criterion:"使用兩表。",anyOf:["CATEGORY","PRODUCT"]},{marks:1,criterion:"正確 JOIN CatID。",anyOf:["JOIN","CATID"]},{marks:1,criterion:"GROUP BY CatName。",anyOf:["GROUPBY","GROUP BY"]},{marks:1,criterion:"HAVING AVG > 100。",anyOf:["HAVING","100"]}],explanation:"WHERE 篩選記錄；平均值屬分組結果，要用 HAVING。",errorType:"SQL 分組錯誤"},
        { id:"q-visual-eb-network",topicId:"eb-1",syllabusRef:"Elective B(a)",difficulty:"standard",marks:5,type:"short-answer",question:"根據網絡圖配對 DHCP、domain controller、proxy、web 及 database server 的資料流。",visual:{type:"network",title:"機構服務",nodes:["Clients","DHCP","Domain","Proxy","Web","Database","Internet"],links:[["Clients","DHCP"],["Clients","Domain"],["Clients","Proxy"],["Proxy","Internet"],["Clients","Web"],["Web","Database"]]},answer:"Clients 從 DHCP 取得網絡設定，向 Domain 認證；外網請求經 Proxy；Web 回應 HTTP 並由 server-side 程式向 Database 查詢。",markingScheme:[{marks:1,criterion:"DHCP 配發設定。",anyOf:["DHCP","IP"]},{marks:1,criterion:"Domain 處理認證。",anyOf:["Domain","認證","登入"]},{marks:1,criterion:"Proxy 代表 client 存取 Internet。",anyOf:["Proxy","Internet"]},{marks:1,criterion:"Web 回應 HTTP。",anyOf:["Web","HTTP"]},{marks:1,criterion:"Web／server script 查詢 Database。",anyOf:["Database","查詢"]}],explanation:"依箭嘴方向交代 request、服務和 response。",errorType:"伺服器角色混淆"},
        { id:"q-visual-eb-web",topicId:"eb-2",syllabusRef:"Elective B(b)",difficulty:"standard",marks:5,type:"short-answer",question:"分析註冊頁的 client／server 分工，提出一項 validation 和兩項安全改善。",visual:{type:"webpage",title:"註冊頁",regions:["Email [________]","Password [________]","Role: Admin / Student","Submit","JavaScript: only presence check","Server: INSERT using concatenated text"]},answer:"Client 可即時檢查格式；server 必須重新驗證。Role 不應由使用者任意選 Admin，須按授權決定；SQL 應用參數化查詢，密碼要安全雜湊且使用 HTTPS。",markingScheme:[{marks:1,criterion:"提出 email format 等 validation。",anyOf:["email","format","格式"]},{marks:1,criterion:"Server 必須重新驗證。",anyOf:["server","再次驗證"]},{marks:1,criterion:"Role 由授權控制。",anyOf:["Role","Admin","授權"]},{marks:1,criterion:"使用參數化查詢。",anyOf:["參數化","prepared","SQL injection"]},{marks:1,criterion:"密碼雜湊或 HTTPS。",anyOf:["雜湊","hash","HTTPS"]}],explanation:"客戶端檢查改善體驗，但所有安全決定都要在伺服器執行。",errorType:"網頁安全分工錯誤"},
        { id:"q-visual-ec-trace",topicId:"ec-1",syllabusRef:"Elective C(a)",difficulty:"advanced",marks:5,type:"short-answer",question:"追蹤 insertion sort 的第一、第二輪，並說明它和 selection sort 的主要差異。",visual:{type:"trace",title:"Insertion sort",columns:["初始","第 1 輪","第 2 輪"],rows:[["[8,3,6,2]","[3,8,6,2]","?"]]},answer:"第二輪把 6 插入 [3,8]，結果 [3,6,8,2]。Insertion sort 把 current item 插入已排序部分並可能多次移位；selection sort 每輪在未排序部分找極值後通常交換一次。",markingScheme:[{marks:2,criterion:"第二輪結果 [3,6,8,2]。",anyOf:["3,6,8,2","[3,6,8,2]"]},{marks:1,criterion:"Insertion 插入已排序部分。",anyOf:["插入","已排序"]},{marks:1,criterion:"可能移動多項。",anyOf:["移位","多項"]},{marks:1,criterion:"Selection 找極值再交換。",anyOf:["selection","極值","交換"]}],explanation:"兩者都逐步擴大已排序部分，但選取和移動方式不同。",errorType:"排序追蹤錯誤"},
        { id:"q-visual-ec-device",topicId:"ec-2",syllabusRef:"Elective C(b)",difficulty:"advanced",marks:5,type:"short-answer",question:"根據折線資料設計風扇事件規則，並提出兩項處理 sensor 噪聲的方法。",visual:{type:"chart",title:"每分鐘溫度",labels:["09:00","09:01","09:02","09:03","09:04","09:05"],values:[28,29,31,30,32,27],unit:"°C"},answer:"可設定高於 30°C 開風扇、低於 28°C 關閉，以兩閾值形成 hysteresis。另可用連續多次超標才觸發、移動平均、範圍檢查或 timeout。",markingScheme:[{marks:1,criterion:"高於 30 開啟。",anyOf:["30","開"]},{marks:1,criterion:"低於 28 關閉。",anyOf:["28","關"]},{marks:1,criterion:"說明 hysteresis。",anyOf:["hysteresis","兩個閾值","頻繁"]},{marks:1,criterion:"第一項噪聲處理。",anyOf:["連續","平均","範圍"]},{marks:1,criterion:"第二項不同處理。",anyOf:["timeout","超時","多次","平滑"]}],explanation:"單一讀值容易受噪聲影響，控制規則要避免頻繁切換並處理失效。",errorType:"感應器事件設計不足"}
    ];
    additions.push(...visualQuestions);

    function makeMcq(id, topicId, profile, factory, context, serial){
        const raw=[factory.correct,...factory.distractors];
        const shift=serial%4;
        const rotated=raw.map((_,index)=>raw[(index+shift)%4]);
        const correctIndex=rotated.indexOf(factory.correct);
        return {id,topicId,syllabusRef:profile.ref,difficulty:["foundation","standard","advanced"][serial%3],marks:1,type:"mcq",question:`${context}情境：${factory.prompt}`,options:rotated.map((label,index)=>({value:letters[index],label})),answer:letters[correctIndex],markingScheme:[{marks:1,criterion:factory.explanation}],explanation:factory.explanation,errorType:factory.errorType,generated:true};
    }

    function makeShort(id, topicId, profile, factory, context, serial){
        const markingScheme=factory.points.map(([criterion,anyOf])=>({marks:1,criterion,anyOf}));
        return {id,topicId,syllabusRef:profile.ref,difficulty:["standard","advanced","foundation"][serial%3],marks:markingScheme.length,type:factory.type,question:`${context}情境：${factory.prompt}`,answer:factory.answer,markingScheme,explanation:`作答時要逐項回應：${markingScheme.map(point=>point.criterion).join("；")}`,errorType:factory.errorType,generated:true};
    }

    function fillToTargets(groupCode, topics, targetMcq, targetNon){
        const all=()=>[...base,...additions].filter(question=>topics.includes(question.topicId));
        let mcqNeeded=targetMcq-all().filter(question=>question.type==="mcq").length;
        let nonNeeded=targetNon-all().filter(question=>question.type!=="mcq").length;
        for(let serial=0;serial<mcqNeeded;serial+=1){
            const topicIndex=serial%topics.length,topicId=topics[topicIndex],profile=profiles[topicId],round=Math.floor(serial/topics.length),factory=profile.mcq[round%profile.mcq.length],context=contexts[(round+topicIndex*5)%contexts.length];
            additions.push(makeMcq(`q-gen-${groupCode}-m-${String(serial+1).padStart(3,"0")}`,topicId,profile,factory,context,serial));
        }
        for(let serial=0;serial<nonNeeded;serial+=1){
            const topicIndex=serial%topics.length,topicId=topics[topicIndex],profile=profiles[topicId],round=Math.floor(serial/topics.length),factory=profile.short[round%profile.short.length],context=contexts[(round+topicIndex*7)%contexts.length];
            additions.push(makeShort(`q-gen-${groupCode}-s-${String(serial+1).padStart(3,"0")}`,topicId,profile,factory,context,serial));
        }
    }

    fillToTargets("core",["cha-1","cha-2","cha-3","cha-4","cha-5","chb-1","chb-2","chc-1","chc-2","chc-3","chc-4","chc-5","chd-1","chd-2","chd-3","chd-4","che-1","che-2","che-3"],180,100);
    fillToTargets("ea",["ea-1","ea-2","ea-3"],30,30);
    fillToTargets("eb",["eb-1","eb-2"],30,30);
    fillToTargets("ec",["ec-1","ec-2"],30,30);

    additions.forEach(question=>Object.freeze(question));
    window.HKDSE_ICT_QUESTIONS=Object.freeze([...base,...additions]);
    window.HKDSE_ICT_EXPANDED=true;
})();
